In [3]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) # matrix
print(arr)
print(type(arr))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>


In [61]:
#slicing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) # matrix
print("================\n", arr)

# Example: Extract the second row
row_2 = arr[1, :]
print("================\n", row_2)

row_1 = arr[0, :]
print("================\n", row_1)

row_3 = arr[2, :]
print("================\n", row_3)

col_3 = arr[:, 2]
print("================\n", col_3)

submatrix = arr[0:1, 0:3]
print("================\n", submatrix)

range_elements = arr[0:2, 1:3] # R, C
print("================\n", range_elements)

# Example: Extract every second element from the array
step_elements = arr[:, ::2]
print("================\n", step_elements)

# Example: Extract every second element from the array
step_elements = arr[::2, :]
print("================\n", step_elements)

 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 [5 6 7 8]
 [1 2 3 4]
 [ 9 10 11 12]
 [ 3  7 11]
 [[1 2 3]]
 [[2 3]
 [6 7]]
 [[ 1  3]
 [ 5  7]
 [ 9 11]]
 [[ 1  2  3  4]
 [ 9 10 11 12]]
