In [11]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a)
print(b)
print(a+b)
print(a*b)

[1 2 3 4]
[5 6 7 8]
[ 6  8 10 12]
[ 5 12 21 32]


In [15]:
test = np.array([[91, 92],[93,94]]) # 2D array
print(test)

[[91 92]
 [93 94]]


In [3]:
l1 = [20,30,40]
l2 = [50,60,70]
print(l1+l2)

[20, 30, 40, 50, 60, 70]


In [6]:
l3 = [100, 200, "|"]
l4 = 3
print(l4*l3)

[100, 200, '|', 100, 200, '|', 100, 200, '|']
