In [5]:
a = [30, 40, 50]
b = [5, 5, 3]
print("LIST: ", a+b) #List

import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([5,5,3])
print("ARRAY: ", np.concatenate([arr1, arr2]))

LIST:  [30, 40, 50, 5, 5, 3]
ARRAY:  [1 2 3 5 5 3]


In [19]:
#Concatenate
# Axis0 & Axis1
import numpy as np
arr1 = np.array([[30,40], [50,10]])
arr2 = np.array([[5,5], [3,3]])
print("Axis=0: \n", np.concatenate([arr1, arr2], axis=0))
print("Axis=1: \n", np.concatenate([arr1, arr2], axis=1))


Axis=0: 
 [[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]
Axis=1: 
 [[30 40  5  5]
 [50 10  3  3]]
