In [53]:
import numpy as np

# Generate a 10x5 array with random integers between 1 and 100
data1 = np.random.randint(1, 101, size=(10, 5))

# Generate a 5x5 array with random integers between 1 and 18
data2 = np.random.randint(1, 18, size=(10, 5))

# Concatenate data1 and data2 horizontally
combined_data = np.hstack((data1, data2))

print("Generated Data1:\n", data1)
print("\nGenerated Data2:\n", data2)
print("\nCombined Data Horizontally:\n", combined_data)
sort = np.sort(combined_data)
print("\nSort Combined Data:\n", np.sort(sort))

#SEARCHING
s = np.where(sort==4)
print(s)



Generated Data1:
 [[83 98 48 11 16]
 [ 2 40 74 99 44]
 [84 60 23 26 28]
 [79 53 57  1 32]
 [88 17 91 23 69]
 [72  3 56 52  5]
 [60 79 41 61 31]
 [70 78 44 87 56]
 [57  6 12 34 17]
 [92  2 77  4 21]]

Generated Data2:
 [[10 17 14  3  6]
 [ 9  6  5 12 17]
 [10 16  8 13  6]
 [ 2  6 15 10 17]
 [ 4 17 10  1  2]
 [ 8 12  2 11 10]
 [13 16  3 15  5]
 [13  3  5 10 12]
 [12 12 11  3  6]
 [14 14  9  4  9]]

Combined Data Horizontally:
 [[83 98 48 11 16 10 17 14  3  6]
 [ 2 40 74 99 44  9  6  5 12 17]
 [84 60 23 26 28 10 16  8 13  6]
 [79 53 57  1 32  2  6 15 10 17]
 [88 17 91 23 69  4 17 10  1  2]
 [72  3 56 52  5  8 12  2 11 10]
 [60 79 41 61 31 13 16  3 15  5]
 [70 78 44 87 56 13  3  5 10 12]
 [57  6 12 34 17 12 12 11  3  6]
 [92  2 77  4 21 14 14  9  4  9]]

Sort Combined Data:
 [[ 3  6 10 11 14 16 17 48 83 98]
 [ 2  5  6  9 12 17 40 44 74 99]
 [ 6  8 10 13 16 23 26 28 60 84]
 [ 1  2  6 10 15 17 32 53 57 79]
 [ 1  2  4 10 17 17 23 69 88 91]
 [ 2  3  5  8 10 11 12 52 56 72]
 [ 3  5 13 15 16 31 

In [79]:
#SEARCHING

import numpy as np
ar = np.random.randint(1, 101, size=(10, 5))
print(ar)
s = np.where(ar==93)
print("Found at: ", s)

array2 = np.random.randint(1, 10, size=(3, 3))
print("\n\n", array2)
even = np.where(array2 % 2 == 0 )
print("\nAll Even are:\n", even)

print("\n\n=========== Filter Array =============")
bool_array = np.random.choice([True, False], size=(3, 3))
print(bool_array)
array3 = np.random.randint(1, 10, size=(3, 3))
print("\n\n", array3)

newArr = array3[bool_array]
print("\n\n", newArr)



[[33 47 76 91 96]
 [42 36 49 94 33]
 [87 63 82 72 76]
 [ 9 19 45 83 23]
 [37 93 64 22 24]
 [65 29  9 71 31]
 [96 85 90 54 86]
 [51 99 98  2 49]
 [ 9 93  9 34 67]
 [14 20 62  4 90]]
Found at:  (array([4, 8], dtype=int64), array([1, 1], dtype=int64))


 [[5 9 4]
 [8 9 1]
 [9 6 6]]

All Even are:
 (array([0, 1, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))


=========== Filter Array =============
[[False False  True]
 [False False  True]
 [False  True False]]


 [[7 6 1]
 [5 9 5]
 [8 2 3]]


 [1 5 2]
